apiVersion: apps/v1
kind: Deployment
metadata:
  name:my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bug
  template:
    metadata:
      labels:
        app: bug
    spec:
      containers:
      - name: buggy
        image: 526486072183.dkr.ecr.us-east-1.amazonaws.com/test
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bug
    k8s-app: bug
  name: bug
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: bug
